Сделать первый набор команд для создания фигуры
iamwhoamianamy/flop.net pull request #103
Opened 2022-03-15 12:22 UTC by Strong0-0Mouse

2022-03-15 13:16 UTC, iamwhoamianamy requested changes

2022-03-15 13:16 UTC, iamwhoamianamy commented on flop.net/ViewModel/MainWindowVM.cs
> +
А где....

2022-03-16 09:48 UTC, Strong0-0Mouse commented on flop.net/ViewModel/MainWindowVM.cs
> +
Для реализации необходимы изменения с #78

2022-03-17 05:14 UTC, iamwhoamianamy requested changes

2022-03-18 13:11 UTC, closed without merging